# Generated by Django 3.1.7 on 2021-03-23 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('sell', 'sell'), ('buy', 'buy')], max_length=4)),
                ('base_currency', models.CharField(choices=[('TOMAN', 'TOMAN'), ('USDT', 'USDT')], max_length=10)),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('traded_amount', models.FloatField(default=0)),
                ('date', models.DateTimeField()),
                ('expire_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='five_min_candle',
            name='close_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='five_min_candle',
            name='open_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='one_day_candle',
            name='close_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='one_day_candle',
            name='open_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='one_min_candle',
            name='close_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='one_min_candle',
            name='open_time',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('TOMAN', 'TOMAN'), ('USDT', 'USDT')], max_length=10)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buys', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
