# Generated by Django 3.1.7 on 2021-03-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20210324_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='five_min_candle',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='one_day_candle',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='one_min_candle',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='five_min_candle',
            name='close_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='five_min_candle',
            name='open_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='one_day_candle',
            name='close_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='one_day_candle',
            name='open_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='one_min_candle',
            name='close_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='one_min_candle',
            name='open_time',
            field=models.IntegerField(),
        ),
    ]
