# Generated by Django 3.1.7 on 2021-03-23 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20210324_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='five_min_candle',
            name='volume',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='one_day_candle',
            name='volume',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='one_min_candle',
            name='volume',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
