# Generated by Django 3.1.7 on 2021-03-27 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20210324_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 9, 58, 3, 175621, tzinfo=utc)),
        ),
    ]
