# Generated by Django 3.1.7 on 2021-03-27 14:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20210327_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 14, 18, 28, 127939, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_transactions', to='exchange.order'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 14, 18, 28, 128402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='exchange.order'),
        ),
    ]
